services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: stefanini_php
        volumes:
            - .:/var/www/html
        networks:
            - app-stefanini-network

    nginx:
        image: nginx:alpine
        container_name: stefanini_nginx
        ports:
            - "8080:80"
        expose:
            - "80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-stefanini-network

    redis:
        image: redis:alpine
        container_name: stefanini_redis
        ports:
            - 6379:6379
        networks:
            - app-stefanini-network
    mysql:
        image: mysql:5.7
        container_name: stefanini_mysql
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: stefanini
            MYSQL_USER: stefanini
            MYSQL_PASSWORD: stefanini
            MYSQL_ROOT_PASSWORD: stefanini
        ports:
            - 3306:3306
        networks:
            - app-stefanini-network

networks:
    app-stefanini-network:
        driver: bridge
