services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: stefanini_php
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-stefanini-network

    redis:
        image: redis:alpine
        container_name: stefanini_redis
        ports:
            - 6379:6379
        networks:
            - app-stefanini-network
    mysql:
        image: mysql:5.7
        container_name: stefanini_mysql
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: stefanini
            MYSQL_USER: stefanini
            MYSQL_PASSWORD: stefanini
            MYSQL_ROOT_PASSWORD: stefanini
        ports:
            - 3306:3306
        networks:
            - app-stefanini-network

    pgsql:
        image: postgres:latest
        container_name: stefanini_pgsql
        environment:
            POSTGRES_PASSWORD: stefanini
            POSTGRES_USER: stefanini
            POSTGRES_DB: stefanini
        ports:
            - 5431:5432
        networks:
            - app-stefanini-network

networks:
    app-stefanini-network:
        driver: bridge
