name: Run PHP Tests with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_URL: http://stefanini_nginx
      APP_KEY: ${{ secrets.APP_KEY }}
      DB_CONNECTION: mysql
      DB_HOST: stefanini_mysql
      DB_PORT: 3306
      DB_DATABASE: stefanini
      DB_USERNAME: stefanini
      DB_PASSWORD: stefanini
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      SENTRY_LARAVEL_DSN: ${{ secrets.SENTRY_LARAVEL_DSN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean vendor
        run: rm -rf vendor/

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Copy .env file
        run: docker compose exec -T app cp .env.example .env

      - name: Clean vendor
        run: rm -rf vendor/

      - name: Composer Install (host)
        run: composer install --no-interaction --prefer-dist

      - name: Run Migrations
        run: docker compose exec -T app php artisan migrate --force || true


      - name: Injetar APP_URL via secret
        run: docker compose exec -T app bash -c "echo APP_URL=${{ secrets.APP_URL }} >> .env"

      - name: Injetar APP_KEY via secret
        run: docker compose exec -T app bash -c "echo APP_KEY=${{ secrets.APP_KEY }} >> .env"

      - name: Injetar DB_CONNECTION via secret
        run: docker compose exec -T app bash -c "echo DB_CONNECTION=${{ secrets.DB_CONNECTION }} >> .env"

      - name: Injetar DB_HOST via secret
        run: docker compose exec -T app bash -c "echo DB_HOST=${{ secrets.DB_HOST }} >> .env"

      - name: Injetar DB_PORT via secret
        run: docker compose exec -T app bash -c "echo DB_PORT=${{ secrets.DB_PORT }} >> .env"

      - name: Injetar DB_DATABASE via secret
        run: docker compose exec -T app bash -c "echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env"

      - name: Injetar DB_USERNAME via secret
        run: docker compose exec -T app bash -c "echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> .env"

      - name: Injetar DB_PASSWORD via secret
        run: docker compose exec -T app bash -c "echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env"

      - name: Injetar SENTRY_LARAVEL_DSN via secret
        run: docker compose exec -T app bash -c "echo SENTRY_LARAVEL_DSN=${{ secrets.SENTRY_LARAVEL_DSN }} >> .env"

      - name: Injetar OPENWEATHERMAP_API_KEY via secret
        run: docker compose exec -T app bash -c "echo OPENWEATHERMAP_API_KEY=${{ secrets.OPENWEATHERMAP_API_KEY }} >> .env"

      - name: Run Tests
        run: docker compose exec -T app php artisan test

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.yml down
