name: Run PHP Tests with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      APP_URL: http://stefanini_nginx
      APP_KEY: ${{ secrets.APP_KEY }}
      DB_CONNECTION: mysql
      DB_HOST: stefanini_mysql
      DB_PORT: 3306
      DB_DATABASE: stefanini
      DB_USERNAME: stefanini
      DB_PASSWORD: stefanini

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Debug container logs if PHP container fails
        run: docker compose logs stefanini_php

      - name: Composer Install
        run: docker compose exec -T stefanini_php composer install --no-interaction

      - name: Copy .env file
        run: docker compose exec -T stefanini_php cp .env.example .env

      - name: Run Migrations
        run: docker compose exec -T stefanini_php php artisan migrate --force || true

      - name: Run Tests
        run: docker compose exec -T stefanini_php ./vendor/bin/phpunit

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.yml down
