name: Run PHP Tests with Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_URL: http://stefanini_nginx
      APP_KEY: ${{ secrets.APP_KEY }}
      DB_CONNECTION: mysql
      DB_HOST: stefanini_mysql
      DB_PORT: 3306
      DB_DATABASE: stefanini
      DB_USERNAME: stefanini
      DB_PASSWORD: stefanini
      OPENWEATHERMAP_API_KEY: ${{ secrets.OPENWEATHERMAP_API_KEY }}
      SENTRY_LARAVEL_DSN: ${{ secrets.SENTRY_LARAVEL_DSN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d --build

      - name: Dekete vendor folder to avoid conflicts
        run: docker compose exec -T app rm -f vendor
      
      - name: Clean vendor folder
        run: rm -rf vendor/
        
      - name: Composer Install (at host)
        run: composer install --no-interaction --no-scripts

      - name: Copy .env file
        run: docker compose exec -T app cp .env.example .env

      - name: Run Migrations
        run: docker compose exec -T app php artisan migrate --force || true

      - name: Run Tests
        run: docker compose exec -T app php artisan test

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.yml down
